export const initialFormState = {
  today: '',
  fullname_kana: '',
  fullname: '',
  birthday: '',
  sex: '',
  age: '',
  address_kana: '',
  postcode: '',
  address: '',
  address3: '',
  tel: '',
  mobile: '',
  email: '',
  contact_address_kana: '',
  contact_postcode: '',
  contact_address: '',
  contact_address3: '',
  contact_tel: '',
  contact_mobile: '',
  contact_email: '',
  graduation_y: '',
  graduation_m: '',
  school: '',
  other_acad: '',
  other_comp: '',
  pr: '',
  toeic: '',
  toefl: '',
  sep: '',
  english: '',
  foreign_lang: '',
  pc_os: '',
  pc_soft: '',
  pc_hotelsoft: '',
  pc_othersoft: '',
  other_pr: '',
  hours: '',
  minutes: '',
  people: '',
  haigu: '',
  fuyou: '',
  hope: '',
};

export const initialFormStateCareers = {
  start_period_y: '',
  start_period_m: '',
  company_name: '',
  end_period_y: '',
  end_period_m: '',
  bumon: '',
  syokusyu: '',
  yakusyoku: '',
  employ_type: '',
  comment: '',
};